Afficher les points de distribution alimentaire sur la cartographie
MTES-MCT/action-bidonvilles-api pull request #23
Opened 2020-11-25 10:12 UTC by gaeldestrem

2020-11-26 16:31 UTC, anis requested changes
Quelques demandes de changements de forme.

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                id: {
La nomenclature appliquée pour les ids sur les autres tables c'est : `nomDeLaTable_id`, donc là ce serait `poi_id`

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    allowNull: true,
Il peut être nul pour le moment ?

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    allowNull: true,
Pareil, ça peut être nul ? Il faut faire attention parce que `created_at` et `updated_at` sont des noms "réservés" pour Sequelize, et il est pas impossible qu'il remplisse la colonne par défaut si elle est nulle ?

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.ARRAY(Sequelize.TEXT) ,
Top ! 👍

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
`TEXT` c'est pour les textes longs, si on parle d'une chaîne de moins de 250 caractères, `STRING` est plus adapté

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
Pareil, peut être plutôt `STRING` ici

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
Pareil, plutôt `STRING` ici

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
C'est pas un booléen ?

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
`STRING` (déso, c'est de plus en plus concis haha)

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
`STRING`

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +            const toBool = val => val === 'TRUE' ? true:false
ça peut être réduit à : `val => val === 'TRUE'`

2020-11-26 16:31 UTC, anis commented on db/migrations/000099-01-create-table-poi.js
> +            'poi',
Les règles de nommage font que les tables sont au pluriel normalement, donc plutôt `pois` (même si ça fait bizarre 🤔 )

2020-11-26 16:31 UTC, anis commented on server/controllers/poiController.js
> +        const results = (await models.poi.findAll());
J'ai l'habitude de mettre un try catch pour retourner une erreur en cas de fail de la requête :
```
try { 
    await models.poi.findAll();
} catch (error) {
    return res.status(500).send({ user_message: 'Une erreur est survenue lors de la lecture en base de données', });
}

2020-11-26 16:31 UTC, anis commented on server/loaders/routesLoader.js
> +        '/poi/',
La syntaxe REST serait plutôt `/pois`

2020-11-26 16:31 UTC, anis commented on server/models/poiModel.js
> +            'Colis Alimentaire'=ANY(categories)`,
Marrant, je connaissais pas cette syntaxe 😄

2020-11-27 14:32 UTC, gaeldestrem commented on db/migrations/000099-01-create-table-poi.js
> +                    type: Sequelize.TEXT,
Nop, c'est un peu bizarre mais c'est un texte d'info

2020-11-27 14:47 UTC, gaeldestrem commented on server/models/poiModel.js
> +            'Colis Alimentaire'=ANY(categories)`,
Je voulais faire une intersection de ['Distribution Alimentaire, 'Colis Alimentaire'] et du tableau de catégories, j'ai trouvé cette syntaxe @google. T'utilises quel syntaxe ?

2020-11-27 14:49 UTC, gaeldestrem commented on db/migrations/000099-01-create-table-poi.js
> +                    allowNull: true,
J'ai renommé ca en `solinum_created_at`/`solinum_updated_at` pour éviter de potentiels conflits. Et oui, il y'a des champs qui ont pas cette data définie dans le csv

2020-11-30 09:53 UTC, merged