(642) Mail 'X vous invite à découvrir la plateforme'
MTES-MCT/action-bidonvilles-api pull request #33
Opened 2021-01-18 17:14 UTC by ch-benard

**Ajout de:**
- server/controllers/inviteController.js
- server/mails/invitation.js

**Modification de:**
- server/loaders/routesLoader.js
```bash
++     app.post(
++        '/invite',
++        middlewares.validation,
++        controllers.invite.invite,
++    );
```

2021-01-19 16:19 UTC, anis requested changes
Il manque la validation des inputs dans le controller invite.invite, ainsi que quelques corrections dans le mail.

2021-01-19 16:19 UTC, anis commented on server/controllers/inviteController.js
> +        } = req.body;
Il faudrait valider que les données sont conformes à la structure attendue !
Vérifier que :
- `guests` est un array
- `guests` contient au moins un élément
- pour chaque élément de l'array, vérifier que la structure est bonne :
- - `email` est un email valide
- - `email` ne correspond pas à un utilisateur qui existe déjà en base de données
- - `first_name` est une string non vide
- - `last_name` est une string non vide

Théoriquement, tu devrais également valider que `greeter` est valide mais je vois que tu envoies un objet avec `first_name`, `last_name`, etc.
En faisant la relecture, je réalise que j'aurais plutôt envoyé juste le user_id du greeter, puis vérifié que cet id correspond bien à un user dans la base de données, auquel cas tu peux y récupérer les infos nécessaires (prénom, nom, etc.).
Double avantage : la validation devient plus simple (tu n'as pas à vérifier que first_name est une string, last_name une string, etc.) et plus sûre.

Pour faire la validation, je rajouterais un middleware (comme pour la création d'un user).

2021-01-19 16:19 UTC, anis commented on server/controllers/inviteController.js
> +        await sendEmailsInvitations(guests, greeter);
il faudrait un try catch ici pour retourner un message d'erreur en cas de problème (à priori, `sendEmailsInvitations` ne renvoit pas d'exception, mais c'est plus une bonne pratique qu'autre chose).

2021-01-19 16:19 UTC, anis commented on server/controllers/inviteController.js
> +        await sendMail(guest, MAIL_TEMPLATES.invitation(guest));
Il faudrait un try/catch ici pour gérer une erreur d'envoi : dans l'idéal il faudrait essayer d'envoyer tous les mails, et pour ceux qui ne partent pas, tant pis, on loggue l'erreur quelque part et puis c'est tout.
Seulement, pour l'instant sans instance Sentry on a nulle part où logguer l'erreur.
Donc tu peux mettre un try/catch, et dans le catch faire un console.log de l'erreur, en dépannage temporaire.

2021-01-19 16:19 UTC, anis commented on server/mails/invitation.js
> +                                    Vous aussi vous voulez contribuer à la résorption des bidonvilles ? <a href="https://resorption-bidonvilles.beta.gouv.fr/#/contact">Demandez dès à présent votre ac
Il ne faut pas mettre l'URL absolue en dur ici, il y a une variable dans la conf pour l'url du front : `${frontUrl}/contact`

2021-01-19 16:19 UTC, anis commented on server/mails/invitation.js
> +        Bouton fond bleu 0/0/145 comme sur les autres mail qui renvoi vers la landing page
Il faut retirer cette ligne !

2021-01-19 16:19 UTC, anis commented on server/mails/invitation.js
> +        Vous aussi vous voulez contribuer à la résorption des bidonvilles ? Demandez dès à présent votre accès : https://resorption-bidonvilles.beta.gouv.fr/#/contact
Il ne faut pas mettre l'URL absolue en dur ici, il y a une variable dans la conf pour l'url du front : `${frontUrl}/contact`

2021-01-19 16:20 UTC, anis commented on server/controllers/inviteController.js
> +        await sendMail(guest, MAIL_TEMPLATES.invitation(guest));
Pourquoi mettre le guest et le greeter dans le même objet ?
Tu pourrais faire deux objets séparés, qui seront deux arguments séparés à envoyer au template mail ?

2021-01-19 16:21 UTC, anis commented on server/mails/invitation.js
> +module.exports = guest => ({
Doublon avec ma remarque au-dessus mais c'est bizarre d'avoir un seul argument qui s'appelle "guest" et dans lequel on retrouve le greeter, je trouve ?

2021-01-20 13:15 UTC, ch-benard commented on server/controllers/inviteController.js
> +        await sendMail(guest, MAIL_TEMPLATES.invitation(guest));
Ok. Il faudrait aussi revoir le code de `server/utils/mail.js` car la méthode `send` ne catch pas les erreurs. Si un envoi n'aboutit pas, l'erreur ne peut donc pas remonter jusqu'à ce contrôleur.

2021-01-20 13:17 UTC, ch-benard commented on server/controllers/inviteController.js
> +        } = req.body;
Même commentaire concernant la méthode `send` de `server/utils/mail.js`.

2021-02-19 15:14 UTC, ch-benard commented on server/controllers/inviteController.js
> +        await sendMail(guest, MAIL_TEMPLATES.invitation(guest));
J'utilise désormais un objet _data_ qui contient deux objets: _guest_ et _greeter_.

2021-02-19 15:14 UTC, ch-benard commented on server/mails/invitation.js
> +module.exports = guest => ({
Voir ci-dessus.

2021-02-19 15:16 UTC, ch-benard commented on server/mails/invitation.js
> +        Vous aussi vous voulez contribuer à la résorption des bidonvilles ? Demandez dès à présent votre accès : https://resorption-bidonvilles.beta.gouv.fr/#/contact
C'est corrigé.

2021-02-19 15:16 UTC, ch-benard commented on server/mails/invitation.js
> +        Bouton fond bleu 0/0/145 comme sur les autres mail qui renvoi vers la landing page
Effectivement. C'est corrigé.

2021-02-19 15:17 UTC, ch-benard commented on server/mails/invitation.js
> +                                    Vous aussi vous voulez contribuer à la résorption des bidonvilles ? <a href="https://resorption-bidonvilles.beta.gouv.fr/#/contact">Demandez dès à présent votre ac
C'est corrigé.

2021-02-19 15:18 UTC, ch-benard commented on server/controllers/inviteController.js
> +        await sendMail(guest, MAIL_TEMPLATES.invitation(guest));
C'est juste: c'est corrigé.

2021-03-03 17:25 UTC, anis requested changes

2021-03-03 17:25 UTC, anis commented on server/controllers/inviteController.js
> +        } = req.body;
On ne s'est pas compris désolé, pour la validation, je parlais de rajouter un fichier `/server/middlewares/validators/invite.js` dans lequel toutes les conditions de validation seraient définies, et utiliser ce middleware dans la définition de la route.
Le contrôleur n'est censé faire aucune vérification et part du principe que les données reçues sont valides et se contente de "faire le métier".

2021-03-03 17:25 UTC, anis commented on server/loaders/routesLoader.js
> +        middlewares.validation,
Il n'y a pas besoin du middleware validation si tu ne mets pas un middleware qui définit les règles de validation juste avant !
Tu devrais avoir un truc du genre ici :
```
app.post(
    '/invite',
    validators.invite,
    middlewares.validation,
    controlleurs.invite.invite
)
```

2021-03-03 17:25 UTC, anis commented on server/mails/invitation.js
> +module.exports = data => ({
Je m'attends à ce que les paramètres soient `(guest, greeter)` pour bien séparer les données. C'est optionnel, en l'état ça reste beaucoup mieux que la v1.

2021-03-30 13:18 UTC, merged