(709) Obligation d'accepter la charte d'utilisation et de ne pas divu…
MTES-MCT/action-bidonvilles-api pull request #38
Opened 2021-02-08 19:16 UTC by ch-benard

2021-02-12 10:42 UTC, anis requested changes
Deux petits détails

2021-02-12 10:42 UTC, anis commented on server/models/userModel.js
> +        // charte_engagement_a_jour: latestCharte === null || user.charte_engagement_signee === latestCharte || user.role !== 'national_admin',
pas besoin de conserver l'ancienne version commentée, tu peux supprimer la ligne directement

2021-02-12 10:42 UTC, anis commented on server/controllers/userController.js
> +            return res.status(500).send({
Utiliser le code `400` ici. Le 500 indique une erreur serveur, là c'est une erreur d'input.

2021-02-15 09:18 UTC, ch-benard commented on server/controllers/userController.js
> +            return res.status(500).send({
Oui, merci. copier/coller sans vraie relecture de ma part.

2021-02-15 09:18 UTC, ch-benard commented on server/models/userModel.js
> +        // charte_engagement_a_jour: latestCharte === null || user.charte_engagement_signee === latestCharte || user.role !== 'national_admin',
Ok, c'est corrigé.

2021-03-03 11:30 UTC, merged