Issue/695
MTES-MCT/action-bidonvilles-api pull request #52
Opened 2021-03-09 17:19 UTC by ch-benard

2021-03-22 12:02 UTC, anis requested changes
Modifications obligatoires : certains liens dans le mail ne marchent pas.

2021-03-22 12:02 UTC, anis commented on server/mails/access_request/user/access_activated_welcome.js
> +    Télécharger le guide de l'utilisateur: ${frontUrl}/doc/guide_utilisateur_2021_02.pdf
Le lien ne marche pas parce que `frontUrl` inclus le `/#`, hors le lien `https://frontend.com/#/doc/...` n'est pas reconnu par vue. Le bon lien devrait être `https://frontend.com/doc/...`.

C'est la première fois que le cas se pose à ce jour parce que jusqu'à maintenant les assets pointés par l'api étaient stockés côté api (dans le dossier /assets).
Deux possibilités :
- déplacer le pdf côté api et utiliser `${backUrl}/assets/...`
- modifier config.js pour créer une autre entrée `${frontDocUrl}` que tu utiliserais ici

2021-03-22 12:02 UTC, anis commented on server/mails/access_request/user/access_activated_welcome.js
> +                                                    <a href="${frontUrl}/doc/guide_utilisateur_2021_02.pdf" target="_blank" style="16px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; fon
Même remarque que plus haut : ce lien ne marche pas.

2021-03-29 12:21 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +    Se connecter à la plateforme: ${frontUrl}/#/connexion
Effectivement, le `/#` est indispensable dans l’url, mais en production il est défini dans `frontUrl`.
Corrigé.

2021-03-29 12:22 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +    Partager sur Facebook: https://www.facebook.com/sharer/sharer.php?u=https://resorption-bidonvilles.beta.gouv.fr/#/contact
C'est rectifié.

2021-03-29 12:22 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +    Partager sur Twitter: http://www.twitter.com/share?url=https://resorption-bidonvilles.beta.gouv.fr/#/contact
Corrigé.

2021-03-29 12:22 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +    Nous contacter par mail: mailto://contact@resorption-bidonvilles.beta.gouv.fr
C'est modifié.

2021-03-29 12:23 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +                            Cordialement.<br/>
C'est corrigé.

2021-03-29 13:01 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +    Télécharger le guide de l'utilisateur: ${frontUrl}/doc/guide_utilisateur_2021_02.pdf
Le guide a été déplacé côté API et le chemin adapté en conséquence.

2021-03-29 13:01 UTC, ch-benard commented on server/mails/access_request/user/access_activated_welcome.js
> +                                                    <a href="${frontUrl}/doc/guide_utilisateur_2021_02.pdf" target="_blank" style="16px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; fon
Même correction que ci-dessus.

2021-03-29 13:18 UTC, ch-benard commented on server/controllers/userController.js
> +
Très juste ! C'est corrigé.

2021-03-29 14:48 UTC, merged